const serviceDetails = {
    bookkeeping: ["Financial Accounting – Maintain accurate financial records as per accounting standards", "Bookkeeping Services – Regular recording of transactions, bank reconciliations, and ledger maintenance", "MIS Reporting – Management Information System (MIS) reports for decision-making", "Payroll Processing – Salary computation, TDS deductions, and payslip generation", "Accounts Payable & Receivable – Tracking vendor payments and customer collections", "Financial Statement Preparation – Balance sheet, profit & loss statement, and cash flow analysis", "Virtual CFO Services – Advisory support for startups and businesses in financial planning", "Compliance & Tax Filings – GST, TDS, and Income Tax return preparation"],
    tax: ["Corporate Tax Planning – Optimizing corporate tax liabilities through strategic planning", "GST Compliance – Ensuring proper GST registration, filing, and compliance", "Income Tax Returns – Assistance in filing individual and corporate tax returns", "Tax Audit & Assessment – Handling tax audits and regulatory assessments", "Transfer Pricing – Ensuring compliance with international transfer pricing regulations", "Advance Tax Advisory – Strategic guidance on advance tax payments", "Withholding Tax (TDS/TCS) Compliance – Managing tax deductions and collections at source", "Representation Before Tax Authorities – Assisting in tax disputes and appeals"],
    financial: ["Business Valuation – Determining the fair market value of your business for strategic decision-making", "Fundraising & Investor Relations – Assisting in securing investments through structured fundraising strategies", "Pitch Deck Preparation – Crafting professional and compelling pitch decks for startups and businesses", "Debt & Equity Advisory – Structuring optimal debt-equity balance for financial growth", "Financial Feasibility Studies – Evaluating the financial viability of new projects or business expansions", "Cash Flow & Working Capital Management – Enhancing liquidity and ensuring smooth financial operations", "Risk & Crisis Management – Identifying financial risks and implementing mitigation strategies", "Mergers, Acquisitions & Business Restructuring – Advisory support for corporate transactions and restructuring"],
    audit: ["Statutory Audit – Ensuring compliance with regulatory requirements through financial statement audits", "Internal Audit & Risk Assessment – Evaluating internal controls and mitigating business risks", "Tax Audit – Conducting tax audits as per government regulations to ensure compliance", "GST Audit – Reviewing GST records and filings to ensure accuracy and adherence to GST laws", "Forensic Audit – Investigating financial fraud, misstatements, and irregularities", "Management Audit – Assessing operational efficiency and effectiveness of business processes", "Stock & Inventory Audit – Verifying stock levels and inventory management practices", "Due Diligence Audit – Conducting in-depth financial and operational reviews for M&A transactions", "IFRS & Ind AS Advisory – Assisting in the transition and compliance with international accounting standards"],
    consulting: ["Market Entry Strategy – Assisting businesses in expanding into new markets with a structured approach", "Business Setup & Entity Formation – Guidance on company registration, structuring, and legal compliance", "Startup Advisory – Helping startups with business models, funding strategies, and financial planning", "Operational Efficiency Improvement – Identifying and eliminating inefficiencies in business processes", "Financial Restructuring – Optimizing capital structure and improving financial health", "Regulatory Compliance & Risk Management – Ensuring adherence to laws and mitigating operational risks", "Business Expansion & Growth Strategy – Providing insights for scaling operations and increasing profitability", "Corporate Governance Advisory – Strengthening governance structures for sustainable business growth"],
    secretarial: ["Company Incorporation & Compliance – Assisting in company registration and regulatory compliance", "Filing of ROC Returns – Ensuring timely filing of annual returns and statutory documents with the Registrar of Companies", "Maintenance of Statutory Registers & Records – Managing company records as per legal requirements", "Corporate Governance Advisory – Ensuring compliance with corporate laws and governance best practices", "Share Transfer & Allotment – Handling issuance, transfer, and management of company shares", "Minutes & Board Resolutions – Drafting and maintaining minutes of board and shareholder meetings", "Compliance under FEMA & RBI Regulations – Ensuring adherence to foreign exchange and banking laws", "Winding Up & Closure of Companies – Assisting in voluntary liquidation and dissolution procedures"],
    payroll: ["Payroll Processing – Managing salary calculations, deductions, and disbursements", "Employee Tax Compliance – Ensuring proper TDS deductions and tax filings for employees", "Provident Fund (PF) & Employee State Insurance (ESI) Compliance – Handling statutory contributions and filings", "Preparation of Salary Slips & Reports – Generating detailed payroll statements for employees", "Leave & Attendance Management – Integrating payroll with leave tracking systems", "Bonus & Incentive Calculation – Managing performance-based payouts and statutory bonuses", "Compliance with Labour Laws – Ensuring adherence to labour laws and regulations", "Payroll Audit & MIS Reporting – Conducting payroll audits and generating insightful reports"],
    startup: ["Business Registration & Structuring – Assisting startups and SMEs in choosing the right legal entity and registration", "Pitch Deck & Fundraising Advisory – Crafting compelling pitch decks and strategies for attracting investors", "DPIIT Registration & Government Benefits – Helping startups register with DPIIT to avail tax benefits and incentives", "Financial Planning & Budgeting – Developing financial strategies for sustainable growth", "Regulatory Compliance & Licensing – Ensuring adherence to statutory and industry-specific regulations", "Accounts & Taxation Management – Providing bookkeeping, tax planning, and GST compliance support", "Funding & Valuation Support – Assisting in startup valuation, investment structuring, and fundraising", "Business Growth & Expansion Strategy – Creating tailored strategies for scaling operations and increasing profitability"]
};

function openModal(service) {
    document.getElementById("modal-title").innerText = service.replace(/_/g, ' ');
    const services = serviceDetails[service];
    let listItems = '';
    services.forEach(service => {
        listItems += `<li>${service}</li>`;
    });
    document.getElementById("modal-text").innerHTML = listItems;
    document.getElementById("modal").style.display = "flex";
}
function closeModal() {
    document.getElementById("modal").style.display = "none";
}